// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Thomas Li",
            "url": "http://about.thomasli.work",
            "email": "dev@stdx.space"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Health Checking for API services",
                "produces": [
                    "application/json"
                ],
                "summary": "Health Checking",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/healthz.HealthzResult"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/healthz.HealthzResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "healthz.HealthzResult": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/healthz.HealthzResultDetails"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "error"
                    ],
                    "example": "ok"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "healthz.HealthzResultDetail": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "error"
                    ],
                    "example": "ok"
                }
            }
        },
        "healthz.HealthzResultDetails": {
            "type": "object",
            "properties": {
                "db": {
                    "$ref": "#/definitions/healthz.HealthzResultDetail"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "FolioForge API",
	Description:      "FolioForge API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
